all:
	javac *.java
	java Assignment8

diff1:
	java Assignment8 < input1.txt > actual-output1.txt
	diff actual-output1.txt output1.txt

diff2:
	java Assignment8 < input2.txt > actual-output2.txt
	diff actual-output2.txt output2.txt

diff3:
	java Assignment8 < input3.txt > actual-output3.txt
	diff actual-output3.txt output3.txt	

diff4:
	java Assignment8 < input4.txt > actual-output4.txt
	diff actual-output4.txt output4.txt